name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deps:
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          vendor
        key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.version }}-
    - name: Setup deps
      run: |
        go mod download
        go mod tidy
        go mod vendor

  test:
    needs: ["deps"]
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          vendor
        key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.version }}-
    - name: Setup deps
      run: |
        go mod download
        go mod tidy
        go mod vendor

    - name: Test and Bench
      run: go test -v -bench=. ./...

  build:
    needs: ["deps"]
    strategy:
      matrix:
        version: ['1.18.0', '1.18.1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.version }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          vendor
        key: ${{ runner.os }}-go-${{ matrix.version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.version }}-
    - name: Setup deps
      run: |
        go mod download
        go mod tidy
        go mod vendor

    - name: Build and Run
      run: |
        go build
        go run ./main.go
